# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "524d840f64798fc04e39f7467eda2e81"
name = "Dev Test App Kanna: RM"
application_url = "https://kannadasan.adnabu.net/shopify/redirect-manager"
embedded = true

[access_scopes]
scopes = "read_online_store_navigation,write_online_store_navigation,read_themes,read_markets,read_locales"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://kannadasan.adnabu.net/shopify/auth/callback/redirect-manager"
]

[pos]
embedded = false
